# Generated by Django 3.2.16 on 2023-01-21 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_city', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=0)),
                ('attraction_name', models.CharField(max_length=50)),
                ('attraction_url', models.URLField()),
                ('attraction_imageurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_code', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('budget', models.FloatField(default=0.0)),
                ('destination_airport_code', models.CharField(max_length=3)),
                ('destination_airport_name', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('airline', models.CharField(max_length=50)),
                ('datetime_generated', models.DateTimeField()),
                ('rank', models.IntegerField(default=0)),
                ('attraction_name', models.CharField(max_length=50)),
                ('attraction_url', models.URLField()),
                ('attraction_imageurl', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
