# Generated by Django 3.2.16 on 2023-01-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_suggestedattraction_suggesteddestination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='SuggestedAttraction',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.DeleteModel(
            name='SuggestedDestination',
        ),
    ]
